debug: false

# maximum wait for a response to any API request (secs)
timeout_req: 60

# maximum wait for a meeting to be ended after end_meeting is called (secs)
timeout_ending: 30

# maximum wait until the bot starts (secs)
timeout_bot_start: 60

servers:
  test-install:
    url: 'http://amy.blindside-dev.com/bigbluebutton/api'
    secret: 'b7a4172822e3ead1a05859fd06b7f88e'
  bbb-other:
    url: 'http://localhost:3000/bigbluebutton/api'
    secret: 'lka98f52e8akdlsoie400365b55e98s7'
  spec/features/create_meeting.rb:
    url: 'http://amy.blindside-dev.com/bigbluebutton/api'
    secret: 'b7a4172822e3ead1a05859fd06b7f88e'
